# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: ko-KR

early_access: false

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  path_filters:
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/build/**"
    - "!**/dist/**"
    - "!**/.dart_tool/**"
    - "!**/*.g.dart"
    - "!**/*.freezed.dart"
    - "!**/generated/**"
    - "!**/pubspec.lock"

  tools:
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true

  path_instructions:
    - path: "**/*"
      instructions: |
        ## 언어 설정
        모든 리뷰 코멘트는 **반드시 한국어로 작성**해야 합니다.

        ## 커밋 컨벤션
        - 타입: feat/fix/refactor/test/docs/chore
        - 구조적 변경(refactor)과 동작적 변경(feat/fix)은 반드시 분리

    # ── Server (Express + TypeScript) ──
    - path: "apps/server/**/*.ts"
      instructions: |
        ## Express/TypeScript 서버 규칙
        - strict TypeScript 사용 (any 지양)
        - 라우터 → 핸들러 → 서비스 계층 분리
        - 에러는 AppError 클래스로 통일
        - SQL injection 방지: Drizzle ORM 파라미터 바인딩 필수

    - path: "apps/server/src/modules/*/handlers.ts"
      instructions: |
        ## Handler 리뷰 지침
        - 요청 검증 후 서비스 호출만 수행
        - 비즈니스 로직 직접 포함 금지
        - 응답 형식은 공통 response wrapper 사용

    - path: "apps/server/src/modules/*/service.ts"
      instructions: |
        ## Service 리뷰 지침
        - 단일 책임 원칙 준수
        - 외부 의존성은 함수 파라미터로 주입
        - 사이드 이펙트 최소화

    - path: "apps/server/**/*.test.ts"
      instructions: |
        ## 테스트 리뷰 지침
        - TDD (Red-Green-Refactor) 준수
        - 의미 있는 테스트명 (행위 기반)
        - 테스트 독립성 확인

    # ── Mobile (Flutter + Dart) ──
    - path: "apps/mobile/**/*.dart"
      instructions: |
        ## Flutter/Dart 모바일 규칙
        - const 생성자 적극 활용
        - GetX 상태 관리 패턴 준수 (Controller + Binding)
        - 위젯 트리 깊이 최소화 (extract widget)
        - 주석은 한글로 작성

    - path: "apps/mobile/packages/api/**/*.dart"
      instructions: |
        ## API 패키지 리뷰 지침
        - Freezed 모델 사용
        - Dio 클라이언트 에러 핸들링 확인
        - nullable 필드 명시적 처리

    - path: "apps/mobile/apps/wowa/**/*.dart"
      instructions: |
        ## 앱 레이어 리뷰 지침
        - View는 UI만, 로직은 Controller로 분리
        - 라우팅은 GetX Routes 사용
        - 하드코딩 문자열 지양

chat:
  auto_reply: true
